CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description varchar(500),
  requester_id bigint NOT NULL,

  FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  description varchar(2000),
  is_available boolean NOT NULL,
  owner_id bigint NOT NULL,
  request_id bigint,

  FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id bigint NOT NULL,
  booker_id bigint NOT NULL,
  status varchar(10),

  FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
  FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text varchar(1000) NOT NULL,
  item_id bigint NOT NULL,
  author_id bigint NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL,

  FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
  FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);